/**
 * @module
 * Vite plugin that generates a `pages.gen.ts` file with the union of page
 * names found in the pages directory and an augmentation that wires the
 * Hono app type into {@link AppRegistry}.
 */

import { readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'
import type { Plugin } from 'vite'

export interface InertiaPagesOptions {
  /**
   * Directory containing the page components, relative to the Vite project root.
   * @default 'app/pages'
   */
  pagesDir?: string

  /**
   * Output path for the generated `pages.gen.ts` file, relative to the Vite project root.
   * @default 'app/pages.gen.ts'
   */
  outFile?: string

  /**
   * File extensions (without the leading dot) to treat as page components.
   * @default ['tsx']
   */
  extensions?: string[]

  /**
   * Page names to exclude from the generated union.
   * @default ['Layout']
   */
  exclude?: string[]

  /**
   * Path to the Hono app server module relative to the generated file's
   * directory, used in the `import type` declaration. Should resolve to a
   * module whose default export is the Hono app instance.
   * @default './server'
   */
  serverModule?: string

  /**
   * Module specifier for `@hono/inertia` used in the generated declaration.
   * Override only when consuming from a non standard location (e.g. a workspace alias).
   * @default '@hono/inertia'
   */
  packageName?: string
}

/**
 * Vite plugin that generates a typed list of Inertia page components.
 *
 * The generated file declares a `PageName` union type and augments
 * `@hono/inertia`'s {@link AppRegistry} so `PageProps<C>` resolves to the
 * props type of the Hono route that renders `C`.
 */
export function inertiaPages(options: InertiaPagesOptions = {}): Plugin {
  const cwd = process.cwd()
  const pagesDir = resolve(cwd, options.pagesDir ?? 'app/pages')
  const outFile = resolve(cwd, options.outFile ?? 'app/pages.gen.ts')
  const extensions = (options.extensions ?? ['tsx']).map((ext) => '.' + ext)
  const exclude = new Set(options.exclude ?? ['Layout'])
  const serverModule = options.serverModule ?? './server'
  const packageName = options.packageName ?? '@hono/inertia'

  const collect = (): string[] => {
    const pages: string[] = []
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir)) {
        const full = join(dir, entry)
        if (statSync(full).isDirectory()) {
          walk(full)
          continue
        }
        if (!extensions.some((ext) => entry.endsWith(ext))) {
          continue
        }
        const name = relative(pagesDir, full)
          .replace(/\.[^.]+$/, '')
          .replaceAll('\\', '/')
        if (!exclude.has(name)) {
          pages.push(name)
        }
      }
    }
    walk(pagesDir)
    return pages.sort()
  }

  const generate = (): void => {
    const pages = collect()
    const union = pages.length ? pages.map((p) => `'${p}'`).join(' | ') : 'never'
    writeFileSync(
      outFile,
      `// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '${serverModule}'

export type PageName = ${union}

declare module '${packageName}' {
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '${packageName}'
`
    )
  }

  return {
    name: '@hono/inertia:pages',
    buildStart() {
      generate()
    },
    configureServer(server) {
      generate()
      const onChange = (file: string): void => {
        if (file.startsWith(pagesDir) && extensions.some((ext) => file.endsWith(ext))) {
          generate()
        }
      }
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
