import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { bots } from '../data/robots'

const allBotsList = Object.keys(bots)

// Robots.txt string
const userAgentDirectives = allBotsList.map((key) => `User-agent: ${key}`).join('\n')
const robotsTxtString = `${userAgentDirectives}\nDisallow: /\n`

// Regexes constructors
const nonRespectingBots = Object.entries(bots).filter(([, value]) => value?.respect !== 'Yes')
const nonRespectingBotsList = nonRespectingBots.map(([key]) => key)

const content = `// This file is generated by scripts/prebuild.ts. Do not edit manually.
export const ROBOTS_TXT = \`${robotsTxtString}\`;
export const ALL_BOTS = ["${allBotsList.join('", "')}"];
export const NON_RESPECTING_BOTS = ["${nonRespectingBotsList.join('", "')}"];
`

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const outputPath = path.resolve(__dirname, '../generated.ts')
fs.writeFileSync(outputPath, content)

console.log('Successfully generated: src/generated.ts')
