name: ci-auth-js
on:
  push:
    branches: [main]
    paths:
      - 'packages/auth-js/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/auth-js/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --filter './' --filter './packages/auth-js'
      - run: bun --filter './packages/auth-js' build
      - run: bun run test --coverage --project @hono/auth-js
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: auth-js
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
