name: ci-auth-js
on:
  push:
    branches: [main]
    paths:
      - 'packages/auth-js/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/auth-js/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/auth-js
      - run: yarn workspace @hono/auth-js build
      - run: yarn test --coverage --project @hono/auth-js
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: auth-js
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
