name: ci-auth-js
on:
  push:
    branches: [main]
    paths:
      - 'packages/auth-js/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/auth-js/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/auth-js
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/auth-js
      - run: yarn workspace @hono/auth-js build
      - run: yarn test --run --project @hono/auth-js
