name: ci-bun-transpiler
on:
  push:
    branches: [main]
    paths:
      - 'packages/bun-transpiler/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/bun-transpiler/**'

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: .tool-versions
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          cache: true
      - run: pnpm install --filter @hono/bun-transpiler
      - run: pnpm turbo --filter @hono/bun-transpiler build
      - run: bun test packages/bun-transpiler --coverage --coverage-reporter lcov
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: bun-transpiler
