name: ci-class-validator
on:
  push:
    branches: [main]
    paths:
      - 'packages/class-validator/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/class-validator/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run --filter @hono/class-validator build
      - run: bun run --filter @hono/class-validator publint
      - run: bun eslint packages/class-validator
      - run: bun run test --coverage --project @hono/class-validator
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: class-validator
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
