name: ci-class-validator
on:
  push:
    branches: [main]
    paths:
      - 'packages/class-validator/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/class-validator/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/class-validator
      - run: yarn workspace @hono/class-validator build
      - run: yarn test --project @hono/class-validator
