name: ci-event-emitter
on:
  push:
    branches: [main]
    paths:
      - 'packages/event-emitter/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/event-emitter/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run --filter @hono/event-emitter build
      - run: bun run --filter @hono/event-emitter publint
      - run: bun eslint packages/event-emitter
      - run: bun run test --coverage --project @hono/event-emitter
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: event-emitter
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
