name: ci-esbuild-transpiler
on:
  push:
    branches: [main]
    paths:
      - 'packages/esbuild-transpiler/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/esbuild-transpiler/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: bun run --filter @hono/esbuild-transpiler build
      - run: bun run --filter @hono/esbuild-transpiler publint
      - run: bun eslint packages/esbuild-transpiler
      - run: bun run test --coverage --project @hono/esbuild-transpiler
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: esbuild-transpiler
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
