name: ci-event-emitter
on:
  push:
    branches: [main]
    paths:
      - 'packages/event-emitter/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/event-emitter/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/event-emitter
      - run: yarn workspace @hono/event-emitter build
      - run: yarn test --project @hono/event-emitter
