name: ci-esbuild-transpiler
on:
  push:
    branches: [main]
    paths:
      - 'packages/esbuild-transpiler/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/esbuild-transpiler/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --filter './' --filter './packages/esbuild-transpiler'
      - run: bun --filter './packages/esbuild-transpiler' build
      - run: bun run test --coverage --project @hono/esbuild-transpiler
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: esbuild-transpiler
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
