name: ci-firebase-auth
on:
  push:
    branches: [main]
    paths:
      - 'packages/firebase-auth/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/firebase-auth/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --filter './' --filter './packages/firebase-auth'
      - run: bun --filter './packages/firebase-auth' build
      - run: bun run test --coverage --project @hono/firebase-auth
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: firebase-auth
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
