name: ci-firebase-auth
on:
  push:
    branches: [main]
    paths:
      - 'packages/firebase-auth/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/firebase-auth/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/firebase-auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn workspaces focus hono-middleware @hono/firebase-auth
      - run: yarn workspace @hono/firebase-auth build
      - run: yarn test --run --project @hono/firebase-auth
