name: ci-graphql-server
on:
  push:
    branches: [main]
    paths:
      - 'packages/graphql-server/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/graphql-server/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run --filter @hono/graphql-server build
      - run: bun run --filter @hono/graphql-server publint
      - run: bun eslint packages/graphql-server
      - run: bun run test --coverage --project @hono/graphql-server
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: graphql-server
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
