name: ci-graphql-server
on:
  push:
    branches: [main]
    paths:
      - 'packages/graphql-server/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/graphql-server/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/graphql-server
      - run: yarn workspace @hono/graphql-server build
      - run: yarn workspace @hono/graphql-server publint
      - run: yarn test --coverage --project @hono/graphql-server
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: graphql-server
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
