name: ci-node-ws
on:
  push:
    branches: [main]
    paths:
      - 'packages/node-ws/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/node-ws/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/node-ws
      - run: yarn workspace @hono/node-ws build
      - run: yarn workspace @hono/node-ws publint
      - run: yarn test --coverage --project @hono/node-ws
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: node-ws
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
