name: ci-node-ws
on:
  push:
    branches: [main]
    paths:
      - 'packages/node-ws/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/node-ws/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --filter './' --filter './packages/node-ws'
      - run: bun --filter './packages/node-ws' build
      - run: bun run test --coverage --project @hono/node-ws
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: node-ws
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
