name: ci-prometheus
on:
  push:
    branches: [main]
    paths:
      - 'packages/prometheus/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/prometheus/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/prometheus
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
