name: ci-prometheus
on:
  push:
    branches: [main]
    paths:
      - 'packages/prometheus/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/prometheus/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run --filter @hono/prometheus build
      - run: bun run --filter @hono/prometheus publint
      - run: bun eslint packages/prometheus
      - run: bun run test --coverage --project @hono/prometheus
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: prometheus
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
