name: ci-react-renderer
on:
  push:
    branches: [main]
    paths:
      - 'packages/react-renderer/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/react-renderer/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/react-renderer
      - run: yarn workspace @hono/react-renderer build
      - run: yarn workspace @hono/react-renderer publint
      - run: yarn eslint packages/react-renderer
      - run: yarn test --coverage --project @hono/react-renderer
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: react-renderer
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
