name: ci-react-renderer
on:
  push:
    branches: [main]
    paths:
      - 'packages/react-renderer/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/react-renderer/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run --filter @hono/react-renderer build
      - run: bun run --filter @hono/react-renderer publint
      - run: bun eslint packages/react-renderer
      - run: bun run test --coverage --project @hono/react-renderer
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: react-renderer
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
