name: ci-swagger-ui
on:
  push:
    branches: [main]
    paths:
      - 'packages/swagger-ui/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/swagger-ui/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn workspaces focus hono-middleware @hono/swagger-ui
      - run: yarn workspace @hono/swagger-ui build
      - run: yarn test --project @hono/swagger-ui
