name: ci-swagger-ui
on:
  push:
    branches: [main]
    paths:
      - 'packages/swagger-ui/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/swagger-ui/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run --filter @hono/swagger-ui build
      - run: bun run --filter @hono/swagger-ui publint
      - run: bun eslint packages/swagger-ui
      - run: bun run test --coverage --project @hono/swagger-ui
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: swagger-ui
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
