name: ci-sentry
on:
  push:
    branches: [main]
    paths:
      - 'packages/sentry/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/sentry/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --filter './' --filter './packages/sentry'
      - run: bun --filter './packages/sentry' build
      - run: bun --filter './packages/sentry' publint
      - run: bun --filter './packages/sentry' typecheck
      - run: bun eslint packages/sentry
      - run: bun vitest --coverage --project @hono/sentry
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: sentry
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
