name: ci-trpc-server
on:
  push:
    branches: [main]
    paths:
      - 'packages/trpc-server/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/trpc-server/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/trpc-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn workspaces focus hono-middleware @hono/trpc-server
      - run: yarn workspace @hono/trpc-server build
      - run: yarn test --run --project @hono/trpc-server
