name: ci-typia-validator
on:
  push:
    branches: [main]
    paths:
      - 'packages/typia-validator/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/typia-validator/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hono-version: [hono@^3.0.0]
        # hono-version: ['hono@^3.0.0', 'hono@^4.0.0']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn add ${{ matrix.hono-version }} --mode=update-lockfile
      - run: yarn workspaces focus hono-middleware @hono/typia-validator
      - run: yarn workspaces foreach --topological --recursive --from @hono/typia-validator run build
      - run: yarn workspace @hono/typia-validator build
      - run: yarn workspace @hono/typia-validator publint
      - run: yarn eslint packages/typia-validator
      - run: yarn test --coverage --project @hono/typia-validator
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: typia-validator
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
