name: ci-trpc-server
on:
  push:
    branches: [main]
    paths:
      - 'packages/trpc-server/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/trpc-server/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/trpc-server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
