name: ci-unknownutil-validator
on:
  push:
    branches: [main]
    paths:
      - 'packages/unknownutil-validator/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/unknownutil-validator/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/unknownutil-validator
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
