name: ci

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  what-changed:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    permissions:
      contents: 'read'
      actions: 'read'
      pull-requests: 'read'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5
        id: setSHAs
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          run_install: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .tool-versions
      - uses: ./.github/actions/what-changed
        id: set-packages
        with:
          since: ${{ steps.setSHAs.outputs.base }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            .turbo
            packages/*/.cache
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
          run_install: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .tool-versions
      - run: pnpm typecheck
      - run: pnpm lint --cache-strategy content
      - run: pnpm format

  test:
    runs-on: ubuntu-latest
    needs: [what-changed]
    if: ${{ needs.what-changed.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.what-changed.outputs.packages) }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            .turbo
            packages/*/.cache
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          cache: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .tool-versions
          cache: 'pnpm'
      - run: pnpm install --filter @hono/${{ matrix.package }}
      - run: pnpm turbo --filter @hono/${{ matrix.package }} build
      - run: pnpm test --coverage --project @hono/${{ matrix.package }}
        id: test
        if: ${{ matrix.package != 'eslint-config' && matrix.package != 'qwik-city' && matrix.package != 'react-compat' }}
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        if: ${{ matrix.package != 'eslint-config' && matrix.package != 'qwik-city' && matrix.package != 'react-compat' }}
        with:
          fail_ci_if_error: true
          directory: ./coverage
          flags: ${{ matrix.package }}
